// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkjaserwjyeegvdweowj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtramFzZXJ3anllZWd2ZHdlb3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTIxNzUsImV4cCI6MjA2MzU4ODE3NX0.Pt2-ByPnR4oCcQwwkyPMxmSjs4hDu6WgCS1KPkRlWIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);